spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10  # Atur sesuai kebutuhan Anda
  jpa:
    hibernate:
      ddl-auto: update  # Atur sesuai kebutuhan Anda, misalnya 'none', 'create', atau 'update'
    show-sql: true  # Untuk menampilkan SQL yang dieksekusi di konsol (opsional)
  profiles:
    active: dev